[target.i686-unknown-linux-musl]
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Tbogk-kernel/linker.ld",
    "-C", "link-arg=-e", "-C", "link-arg=kernel_entry",
    "-C", "relocation-model=static",
    "-C", "target-feature=-sse,-sse2",
]
